### ISSUE TITLE
Problem about scanning bin.hex file

### ISSUE THREAD

**Issue by ZhichunLu-11** [eth-sri/securify#108]
Hi, I just want to use securify to scan some binary file, but when I find it produce no result.

<pre><font color="#8AE234"><b>alex@ubuntu</b></font>:<font color="#729FCF"><b>~/Downloads/securify-master</b></font>$ java -jar build/libs/securify.jar -fh ./src/test/resources/solidity/UnrestrictedEtherFlow2.bin.hex
  Attempt to decompile the contract with methods...
  Success. Inlining methods...
  Propagating constants...
  Verifying patterns...
</pre>

just like above. 
Is securify can not scan binary file or I did something wrong? 
I will be appreciate if you can solve my problem!

**Comment by ritzdorf** [comment]
Hi @Unlocku,

thank you for contacting us.
This part is not well documented.

Currently you can run:
```
java -jar build/libs/securify.jar --livestatusfile /tmp/out.json  -fh ./src/test/resources/solidity/UnrestrictedEtherFlow2.bin.hex
```
to write the results to `/tmp/out.json` but we will improve this.

**Comment by Unlocku** [comment]
> Hi @Unlocku,
> 
> thank you for contacting us.
> This part is not well documented.
> 
> Currently you can run:
> 
> ```
> java -jar build/libs/securify.jar --livestatusfile /tmp/out.json  -fh ./src/test/resources/solidity/UnrestrictedEtherFlow2.bin.hex
> ```
> 
> to write the results to `/tmp/out.json` but we will improve this.

thanks!
