### ISSUE TITLE
Add docker image to dockerhub

### ISSUE THREAD

**Issue by hiqua** [eth-sri/securify#3]

**Comment by MatthiasEgli-chainsecurity** [comment]
Together with truffle integration lets create a proper account on dockerhub for autoritative securify images

**Comment by hiqua** [comment]
Last I tried, there were some problems with the ownership of the repo, basically you have to be an admin of the github repo or something (so that you can link the dockerhub account with the github account), so I could not do it, maybe @ptsankov could. That begs the question of which namespace we want on Dockerhub, do we want a `eth-sri` (that Petar controls?), or do we want a chainsecurity namespace?

For the chainsecurity namespace, we would have to fork the repo to our github namespace (and sync it whenever we want to build the docker image again).

Also see https://github.com/eth-sri/securify/pull/34#issuecomment-435806099

**Comment by MatthiasEgli-chainsecurity** [comment]
Lets create one from our chainsecurity account for now: https://github.com/ChainSecurity/securify

**Comment by hiqua** [comment]
Actually I worked around the limitation I had encountered, it was enough to convert the chainsecurity namespace on dockerhub to an organization, so it works now with the eth-sri repo.
