### ISSUE TITLE
Report versioning

### ISSUE THREAD

**Issue by hiqua** [eth-sri/securify#62]
We should add a version field to the json report, so that bugs can be traced back to the corresponding commit.

A way to do it would be to somehow insert the Git commit in the build process, so that it is then used when a report is produced.

**Comment by ritzdorf** [comment]
Did you have something like this in mind?
http://mrhaki.blogspot.com/2015/04/gradle-goodness-use-git-commit-id-in.html

**Comment by hiqua** [comment]
Done.
