### ISSUE TITLE
Feature request: let the user specify PATTERN_TIMEOUT

### ISSUE THREAD

**Issue by ggrieco-tob** [eth-sri/securify#73]
Even if you use the `timeout` command to control how much time securify should run, its subprocess (e.g. `mustExplicit`) keep running for a long time. So, It will be very useful to allow the user to specify this timeout:

https://github.com/eth-sri/securify/tree/b43c6573f70412ee252dd881c692141cfb9d3beb/src/main/java/ch/securify/analysis/Config.java#L23

**Comment by hiqua** [comment]
If the timeout is reached, the results are not meaningful, so I think it's fine to wait longer, until the user manually interrupts the process. Or is it rather #15 which is bothering you?

**Comment by ggrieco-tob** [comment]
> Or is it rather #15 which is bothering you?

Yes. Sorry I couldn't find that issue before! Feel free to close this issue if you want.

**Comment by hiqua** [comment]
Great!
