### ISSUE TITLE
Add alternative to specify solc binary manually.

### ISSUE THREAD

**Issue by mattaereal** [eth-sri/securify#76]
Not using the template because this is mostly a feature, not a bug. Everything checks out perfectly.

The thing is that all my workstations systems default solc to v0.5, and when auditing I need to be able to have different versions (0.4.25 for example), otherwise securify crashes because of solc's errors (breaking changess, etc).

Going to add a PR myself after testing it works as intended.

Thanks for your good work :)

**Comment by hiqua** [comment]
Thanks for the PR!
