### ISSUE TITLE
Test samples failed

### ISSUE THREAD

**Issue by fang19911030** [eth-sri/securify#92]
When I tried the command : 
`java -jar build/libs/securify.jar -fs src/test/resources/solidity/transaction-reordering.sol`
I got an error:
![screenshot from 2019-03-01 11-05-21](https://user-images.githubusercontent.com/17070830/53650213-03a91000-3c12-11e9-93dc-8a4d158e522a.png)
Here is the output of command : `solc -version`
**Version: 0.5.2+commit.1df8f40c.Linux.g++**
Thank you.

**Comment by hiqua** [comment]
Do you have the latest version on `master`?

**Comment by fang19911030** [comment]
Sorry， I didn't get your point.  You mean the version of **solc** ?   The solc in my server is not the latest version.

**Comment by hiqua** [comment]
I meant the latest securify version.

**Comment by fang19911030** [comment]
After I pull the newest code, the issue is solved. Thank you.
